changes

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -99,4 +99,10 @@ jobs:
                 aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 520256696060.dkr.ecr.us-east-1.amazonaws.com
                 sudo docker pull ${{ needs.build.outputs.image_name }}
                 sudo docker run -d -p 80:5000 --name myapp ${{ needs.build.outputs.image_name }}
-                echo "Deployed successfully to EC2 instance" 
+                if [ $? -eq 1 ]; then
+                  echo "Deployment failed"
+                  exit 1
+                else
+                  echo "Deployed successfully to EC2 instance"
+                fi
+                
